import java.util.Arrays;
import java.util.List;

public class QuestionRepository {
        public static List<Question> getQuestions() {
                return Arrays.asList(
                                new Question("Qual a capital da Franca?",
                                                new String[] { "Paris", "Londres", "Roma", "Berlim" }, 0),
                                new Question("Quem pintou a Mona Lisa?",
                                                new String[] { "Michelangelo", "Leonardo da Vinci", "Raphael",
                                                                "Donatello" },
                                                1),
                                new Question("Qual e o maior planeta do nosso sistema solar?",
                                                new String[] { "Terra", "Marte", "Jupiter", "Saturno" }, 2),
                                new Question("Em que ano o homem pisou na Lua pela primeira vez?",
                                                new String[] { "1965", "1969", "1971", "1975" }, 1),
                                new Question("Quem escreveu 'Dom Casmurro'?",
                                                new String[] { "Machado de Assis", "Jose de Alencar",
                                                                "Graciliano Ramos", "Jorge Amado" },
                                                0),
                                new Question("Qual e a formula quimica da agua?",
                                                new String[] { "H2O", "CO2", "O2", "H2SO4" }, 0),
                                new Question("Quantos estados tem o Brasil?", new String[] { "24", "25", "26", "27" },
                                                2),
                                new Question("Quem descobriu o Brasil?",
                                                new String[] { "Pedro Alvares Cabral", "Cristovao Colombo",
                                                                "Americo Vespucio",
                                                                "Vasco da Gama" },
                                                0),
                                new Question("Qual e o menor pais do mundo?",
                                                new String[] { "Monaco", "Vaticano", "Malta", "San Marino" }, 1),
                                new Question("Qual e a moeda do Japao?",
                                                new String[] { "Yuan", "Won", "Iene", "Dolar" }, 2),
                                new Question("Qual e o simbolo quimico do ouro?", new String[] { "Au", "Ag", "O", "G" },
                                                0),
                                new Question("Qual e a lingua oficial do Brasil?",
                                                new String[] { "Ingles", "Portugues", "Espanhol", "Frances" }, 1),
                                new Question("Quantos continentes existem no mundo?",
                                                new String[] { "5", "6", "7", "8" }, 2),
                                new Question("Qual e o maior oceano do mundo?",
                                                new String[] { "Atlantico", "Pacifico", "Indico", "Artico" },
                                                1),
                                new Question("Quem e o autor de 'Harry Potter'?",
                                                new String[] { "J.R.R. Tolkien", "George R.R. Martin", "J.K. Rowling",
                                                                "Stephen King" },
                                                2),
                                new Question("Qual e a montanha mais alta do mundo?",
                                                new String[] { "K2", "Everest", "Kangchenjunga", "Lhotse" }, 1),
                                new Question("Qual e o rio mais longo do mundo?",
                                                new String[] { "Nilo", "Amazonas", "Yangtze", "Mississippi" },
                                                1),
                                new Question("Quem pintou o teto da Capela Sistina?",
                                                new String[] { "Raphael", "Donatello", "Leonardo da Vinci",
                                                                "Michelangelo" },
                                                3),
                                new Question("Qual e o maior mamifero do mundo?",
                                                new String[] { "Elefante", "Baleia Azul", "Rinoceronte", "Hipopotamo" },
                                                1),
                                new Question("Quem foi o primeiro presidente do Brasil?",
                                                new String[] { "Getulio Vargas", "Juscelino Kubitschek",
                                                                "Deodoro da Fonseca",
                                                                "Marechal Floriano" },
                                                2));
        }
}